server.port=${PORT:8081}

###############
### Logging ###
###############
logging.level.org.atmosphere = warn
logging.level.reactor.netty.http.client=TRACE
#logging.level.org.springframework.web=TRACE
#logging.file.name=ragsolution.log

##############
### Spring ###
##############
#spring.ai.ollama.init.pull-model-strategy=when_missing
spring.mustache.check-template-location = false
spring.jpa.defer-datasource-initialization = true
spring.threads.virtual.enabled=true

spring.ai.ollama.chat.options.model=granite3.1-dense:2b-instruct-q4_K_M

#### VERTEX AI ####
#spring.ai.vertex.ai.gemini.project-id=sfeir-school-genai
#spring.ai.vertex.ai.gemini.location=europe-west4
#spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.0-flash
#spring.ai.vertex.ai.gemini.chat.options.temperature=0.5

###################
# PGVector
###################
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=myuser
spring.datasource.password=ChangeMe
spring.docker.compose.lifecycle-management=start-only
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.jpa.hibernate.ddl-auto=update

###################
# APP
###################
sensitiveWords=fusil, meurtre
