server.port=${PORT:8080}

###############
### Logging ###
###############
logging.level.org.atmosphere = warn
logging.level.reactor.netty.http.client=TRACE

##############
### Spring ###
##############
spring.mustache.check-template-location = false
spring.jpa.defer-datasource-initialization = true
spring.threads.virtual.enabled=true
