server.port=${PORT:8080}

###############
### Logging ###
###############
logging.level.org.atmosphere = warn
logging.level.org.springframework=TRACE

###############
### Mailing ###
###############
spring.mail.host=localhost
spring.mail.port=2525
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

#################
### Spring ai ###
#################
spring.ai.ollama.init.pull-model-strategy=when_missing
spring.mustache.check-template-location = false
spring.jpa.defer-datasource-initialization = true
spring.threads.virtual.enabled=true

spring.ai.ollama.chat.options.model=llama3-groq-tool-use

#### VERTEX AI ####
#spring.ai.vertex.ai.gemini.project-id=sfeir-school-genai
#spring.ai.vertex.ai.gemini.location=europe-west4
#spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.0-flash
#spring.ai.vertex.ai.gemini.chat.options.temperature=0.5

##############
### Vaadin ###
##############
vaadin.launch-browser=true
# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages = com.vaadin,org.vaadin,com.example.application
vaadin.pnpm.enable=true


###################
# PGVector
###################
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres_db
spring.datasource.username=myuser
spring.datasource.password=ChangeMe
spring.docker.compose.lifecycle-management=start-only
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.jpa.hibernate.ddl-auto=update
###################
# APP
###################
sensitiveWords=fusil, meurtre
