server.port=${PORT:8081}
#spring.config.import=optional:file:./shared.properties,optional:file:../shared.properties
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
##############
### Spring ###
##############
#spring.ai.ollama.init.pull-model-strategy=when_missing
spring.mustache.check-template-location = false
spring.jpa.defer-datasource-initialization = true
spring.threads.virtual.enabled=true

#spring.ai.ollama.chat.options.model=granite3.1-dense:2b-instruct-q4_K_M
spring.ai.ollama.embedding.model=mxbai-embed-large
spring.ai.ollama.chat.model=granite3.1-dense:2b-instruct-q4_K_M
#spring.ai.model.embedding=mxbai-embed-large

#### VERTEX AI ####
#spring.ai.vertex.ai.gemini.project-id=sfeir-school-genai
#spring.ai.vertex.ai.gemini.location=europe-west4
#spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.0-flash
#spring.ai.vertex.ai.gemini.chat.options.temperature=0.5

###################
# PGVector
###################
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres_db
spring.datasource.username=myuser
spring.datasource.password=ChangeMe
spring.docker.compose.lifecycle-management=start-only
spring.ai.vectorstore.pgvector.initialize-schema=false
spring.jpa.hibernate.ddl-auto=update

###################
# APP
###################
sensitiveWords=fusil, meurtre
