server.port=${PORT:8080}

###############
### Logging ###
###############
logging.level.org.atmosphere = warn
logging.level.reactor.netty.http.client=TRACE

##############
### Spring ###
##############
spring.ai.ollama.chat.options.model = llama3.2
spring.mustache.check-template-location = false
spring.jpa.defer-datasource-initialization = true
spring.threads.virtual.enabled=true

##############
### Vaadin ###
##############
vaadin.launch-browser=true
# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages = com.vaadin,org.vaadin,com.example.application
vaadin.pnpm.enable=true


###################
# PGVector
###################
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=myuser
spring.datasource.password=ChangeMe
spring.docker.compose.lifecycle-management=start-only

###################
# APP
###################
sensitiveWords=fusil, meurtre
