global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sfeir-school-spring-ai'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # 'host.docker.internal' permet au conteneur d'accéder à ton localhost (Windows/Mac)
      # Sur Linux, utilise l'adresse IP de ta machine ou --network="host"
      - targets: ['host.docker.internal:8081']